server:
  port: 8088

spring:
  application:
    name: mobile-mobio-client
  main:
      allow-bean-definition-overriding: true
  datasource:
      url: jdbc:mysql://192.168.1.196:3306/venesa_crm
      username: wellness
      password: Wellness#2019
      platform: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      show-sql: false
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl